name: dcuid
description: Collision-resistant ids optimized for horizontal scaling and binary search lookup performance.
version: 0.1.0
homepage: https://github.com/kascote/dcuid
repository: https://github.com/kascote/dcuid
issue_tracker: https://github.com/kascote/dcuid/issues
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  very_good_analysis: ^3.1.0